### ISSUE TITLE
Xhr provider broken in firefox (nightly, at least)

### ISSUE THREAD

**Issue by rsturgell** [google/tracing-framework#516]
I get exceptions:

TypeError: 'type' getter called on an object that does not implement interface Event.

From BaseEventTarget..dispatchEvent when ProxyXMLHttpRequest passes it a funny fake event built with "Object.create(e, {'target': { 'value': self } })".

Maybe 'type' changed from a normal field to a getter and they now verify the type of "this". Ugh.

**Comment by chihuahua** [comment]
Solved with commit 5c3f4531388dbf6d219d9935d4d40d15168795c9.
