### ISSUE TITLE
It's highly insecure to download sauceconnect from HTTPS and then run it unconditionally

### ISSUE THREAD

**Issue by evilaliv3** [google/tracing-framework#548]
Currently [scripts/run-saucelabs.sh](https://github.com/google/tracing-framework/commit/2eee48df2d71514f2eba1f7b0859b61f2357ba1b#diff-2fafa72ce1a02272815a944767979b92R40) downloads sauce-connect via HTTP and then run it without any validation.

**Comment by benvanik** [comment]
:+1:
