### ISSUE TITLE
Stop capture while preserving HUD

### ISSUE THREAD

**Issue by joshduck** [google/tracing-framework#562]
I'd like to automatically capture a small subset of the startup of my application. If I call `wtf.trace.stop()` then the HUD disappears (and the documentation indicates the trace is discarded). Is there some way to preserve the HUD and allow me to use the "Send to UI" feature at a later point in time?

**Comment by benvanik** [comment]
If you call `wtf.trace.snapshot()` where you are currently calling stop it should save off the current snapshot to a file right then. To name the file you can pass `file://myname`. Alternatively you can pass an empty array and the captured buffers will be placed in there so you can save them however you like:
```
var results = [];
wtf.trace.snapshot(results);
results[0];  // binary buffer
```

**Comment by joshduck** [comment]
I was trying to figure out how to pipe that snapshot to the extension (from a page without file access). Looks like `wtf.hud.sendSnapshotToWindow(false)` will do the trick.
